exports.assets = function () {
  return [{
    name: 'Earth',
    type: 'environment',
    subtype: 'planet',
    obj: 'sphere',
    texture: '/public/land_ocean_ice_cloud_2048.jpg',
    x: 0,
    y: 0,
    z: -220000,
    scale: 64,
  }, {
    name: 'Moon',
    type: 'environment',
    subtype: 'moon',
    obj: 'sphere',
    texture: '/public/lroc_color_poles_1k.jpg',
    bump: '/public/usgsmoon.jpg',
    x: 0,
    y: 0,
    z: 28000,
    scale: 16,
  }, {
    name: 'Sun',
    type: 'environment',
    subtype: 'star',
    obj: 'sphere',
    textures: ['/public/lensflare0.png', '/public/lensflare3.png', '/public/lensflare4.png'],
    x: 0,
    y: 0,
    z: 10000000,
    scale: 1,
    lensflares: [{
      texture: 0,
      size: 700,
      distance: 0,
      color: undefined
    }, {
      texture: 1,
      size: 60,
      distance: 0.6,
      color: undefined
    }, {
      texture: 1,
      size: 70,
      distance: 0.7,
      color: undefined
    }, {
      texture: 1,
      size: 120,
      distance: 0.9,
      color: undefined
    }, {
      texture: 2,
      size: 70,
      distance: 1,
      color: undefined
    }]
  }]
}
